---
- name: Create 10 nginx containers on all servers for load balancing 
  hosts: all
  tasks:
    - name: Create 10 nginx containers 
      docker_container:
        name: "container{{item}}"
        image: nginx 
      with_sequence: count=10

