---
- name: Configure apache /httpd based on os 
  hosts: all 
  tasks: 
    - name: Install apache2 on Ubuntu servers
      apt: 
        name: apache2
        state: present 
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on RHEL servers
      yum: 
        name: httpd 
        state: present 
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file 
      include: edit_index.yml 
    - name: Restart apache2 on Ubuntu servers
      service: 
        name: apache2
        state: restarted 
      when: ansible_distribution == "Ubuntu" 
    - name: Restart httpd on RHEL servers
      service: 
        name: httpd 
        state: restarted 
      when: ansible_distribution == "RedHat"
    - name: Check apache/httpd response on all servers
      include: check_apache_response.yml

... 

     
