---
- name: Install jenkins and required s/w's
  hosts: jenkinsserver
  tasks:
    - name: Install required s/w's 
      yum:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: java,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}  
    - name: Download jenkins.war file
      get_url:
        url: https://get.jenkins.io/war-stable/2.414.2/jenkins.war
        dest: /home/ec2-user
- name: Configure tomcat on qa and prodservers
  hosts: servers
  tasks:
    - name: Install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items: 
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}
    - name: copy customised tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: Restart tomcat9
  handlers:
    - name: Restart tomcat9
      service:
       name: tomcat9
       state: restarted

       


  

