---
- name: create user on all managed nodes
  hosts: appserver
  tasks: 
     - name: create a user
       user:
         name: lavanya
         password: sunil
         uid: 2326
         shell: /bin/bash
         comment: "A normal user"
         home: /tmp/lavanya

...
