---
- name: Create users and copy files into users home dirs 
  hosts: all
  tasks: 
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items: 
        - {a: raju,b: sunil,c: /home/raju}
        - {a: rani,b: sunil,c: /tmp/rani}  
    - name: copy files
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/raju}
        - {a: /etc/group,b: /tmp/rani}
...
