---
- name: Implementing tags 
  hosts: all
  tasks:
    - name: Install tree
      apt: 
        name: tree
        state: present 
        update_cache: yes
      tags: tree installation
    - name: Create a user
      user:
        name: sunil
        password: sunil
      tags: user_creation 
    - name: copy passwd file 
      copy:
        src: /etc/passwd
        dest: /tmp 
...





