---
- name: Install git using apt on ubuntu servers
  hosts: ubuntu 
  tasks:
    - name: Install git using apt 
      apt:
        name: git 
        state: present 
        update_cache: yes
- name: Install git using yum on rhel
  hosts: redhat
  tasks:
    - name: Install git using yum 
      yum:
        name: git 
        state: present 
        update_cache: yes 
...

